name: Docker Image CI

on:
  push:
    tags: 
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS }}
    - name: Build && Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./debian/bullseye/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/amd64-debian:${GITHUB_REF:10}
    - name: Build && Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./debian/bullseye/Dockerfile.arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/arm64v8-debian:${GITHUB_REF:10}
