name: Docker Image CI

on:
  push:
    tags: 
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      uses: docker/login-action@v1
      with:
        username: xue8
        password: ${{ secrets.DOCKER_ACCESS }}
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Build && Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./debian/bullseye/Dockerfile
        push: true
        tags: |
          xue8/amd64-debian:${{ steps.get_version.outputs.VERSION }}
    - name: Build && Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./debian/bullseye/Dockerfile.arm64
        push: true
        tags: |
          xue8/arm64v8-debian:${{ steps.get_version.outputs.VERSION }}
