name: Docker Image CI

on:
  push:
    tags: 
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -f debian/bullseye/Dockerfile -t xue8:${GITHUB_REF:10}
    - name: Push the Docker images
      run: docker push xue8:${GITHUB_REF:10}
